"""
PDF Generation Service for Audit Reports.
Uses fpdf2 to create professional legal audit documents.
"""
from fpdf import FPDF
import json
from datetime import datetime

class AuditPDF(FPDF):
    def header(self):
        # Logo/Brand
        self.set_font('helvetica', 'B', 16)
        self.set_text_color(6, 10, 19) # Deep Navy
        self.cell(0, 10, 'LegalShield AI Audit Report', 0, 1, 'L')
        
        # Line
        self.set_draw_color(240, 180, 41) # Gold/Amber
        self.set_line_width(0.5)
        self.line(10, 22, 200, 22)
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('helvetica', 'I', 8)
        self.set_text_color(128, 128, 128)
        date_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        self.cell(0, 10, f'Generated by LegalShield AI on {date_str} - Confidential - Page {self.page_no()}/{{nb}}', 0, 0, 'C')

def generate_audit_pdf(doc_name: str, report_data: dict) -> bytes:
    pdf = AuditPDF()
    pdf.alias_nb_pages()
    pdf.add_page()
    
    # Document Info
    pdf.set_font('helvetica', 'B', 12)
    pdf.set_text_color(50, 50, 50)
    pdf.cell(0, 10, f"Document: {doc_name}", 0, 1)
    pdf.ln(2)
    
    # Summary Section
    pdf.set_fill_color(240, 240, 240)
    pdf.set_font('helvetica', 'B', 11)
    pdf.cell(0, 8, "EXECUTIVE SUMMARY", 0, 1, 'L', fill=True)
    pdf.ln(2)
    pdf.set_font('helvetica', '', 10)
    pdf.set_text_color(0, 0, 0)
    pdf.multi_cell(0, 5, report_data.get('executive_summary', 'No summary available.'))
    pdf.ln(10)
    
    # Risk Profile Details
    pdf.set_font('helvetica', 'B', 11)
    pdf.cell(0, 8, "RISK PROFILE & COMPLIANCE", 0, 1, 'L', fill=True)
    pdf.ln(5)
    
    # Overall Risk Score
    risk_score = report_data.get('overall_risk_score', 'UNKNOWN').upper()
    pdf.set_font('helvetica', 'B', 10)
    pdf.cell(40, 8, "Risk Level:", 0, 0)
    
    # Color code for risk
    if "HIGH" in risk_score: pdf.set_text_color(239, 68, 68)
    elif "MEDIUM" in risk_score: pdf.set_text_color(245, 158, 11)
    elif "LOW" in risk_score: pdf.set_text_color(16, 185, 129)
    else: pdf.set_text_color(100, 100, 100)
    
    pdf.cell(0, 8, risk_score, 0, 1)
    pdf.set_text_color(0, 0, 0)
    
    # Compliance Score
    comp_score = report_data.get('compliance_score', 0.0)
    pdf.set_font('helvetica', 'B', 10)
    pdf.cell(40, 8, "Compliance Score:", 0, 0)
    pdf.set_font('helvetica', '', 10)
    pdf.cell(0, 8, f"{int(comp_score)}%", 0, 1)
    pdf.ln(10)
    
    # Findings Section
    findings = json.loads(report_data.get('findings_json', '[]'))
    if findings:
        pdf.set_font('helvetica', 'B', 11)
        pdf.cell(0, 8, "KEY FINDINGS", 0, 1, 'L', fill=True)
        pdf.ln(5)
        
        for i, f in enumerate(findings, 1):
            # Header
            pdf.set_font('helvetica', 'B', 10)
            risk = f.get('risk_level', 'info').upper()
            
            # Color indicator
            if risk == "HIGH": pdf.set_text_color(239, 68, 68)
            elif risk == "MEDIUM": pdf.set_text_color(245, 158, 11)
            else: pdf.set_text_color(16, 185, 129)
            
            pdf.cell(0, 8, f"{i}. {f.get('title', 'Untitled Finding')} [{risk}]", 0, 1)
            pdf.set_text_color(0, 0, 0)
            
            # Context
            pdf.set_font('helvetica', 'I', 9)
            pdf.set_text_color(100, 100, 100)
            pdf.multi_cell(0, 5, f"Impact: {f.get('description', 'N/A')}")
            pdf.ln(1)
            
            # Recommendation
            pdf.set_font('helvetica', 'B', 9)
            pdf.set_text_color(240, 180, 41) # Gold
            pdf.cell(30, 5, "Recommendation:", 0, 0)
            pdf.set_font('helvetica', '', 9)
            pdf.set_text_color(0, 0, 0)
            pdf.multi_cell(0, 5, f.get('recommendation', 'N/A'))
            
            # Referenced text
            ref = f.get('referenced_text')
            if ref:
                pdf.ln(2)
                pdf.set_font('helvetica', '', 8)
                pdf.set_text_color(120, 120, 120)
                pdf.multi_cell(0, 4, f'Extract: "{ref}"', border='L')
            
            pdf.ln(5)
            
            # Page break if needed
            if pdf.get_y() > 250:
                pdf.add_page()
    
    # Key Clauses Section
    clauses = json.loads(report_data.get('key_clauses_json', '[]'))
    if clauses:
        if pdf.get_y() > 200: pdf.add_page()
        pdf.set_font('helvetica', 'B', 11)
        pdf.cell(0, 8, "KEY PROVISIONS & CLAUSES", 0, 1, 'L', fill=True)
        pdf.ln(5)
        
        for c in clauses:
            pdf.set_font('helvetica', 'B', 10)
            pdf.cell(0, 8, f"{c.get('clause_type', 'Clause')}: {c.get('title', 'Untitled')}", 0, 1)
            
            pdf.set_font('helvetica', '', 9)
            pdf.multi_cell(0, 5, c.get('summary', ''))
            
            ctext = c.get('clause_text')
            if ctext:
                pdf.ln(1)
                pdf.set_font('helvetica', 'I', 8)
                pdf.set_text_color(100, 100, 100)
                pdf.multi_cell(0, 4, f'Text: "{ctext}"', border='L')
            
            pdf.ln(4)
            if pdf.get_y() > 250: pdf.add_page()

    return bytes(pdf.output())
