from fpdf import FPDF
import os
from datetime import datetime

class SEOPDFReport(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 15)
        self.cell(0, 10, "Geo-Sentinel SEO Audit Report", 0, 1, "C")
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.cell(0, 10, f"Page {self.page_no()} | Generated by Geo-Sentinel Auditor", 0, 0, "C")

def safe_text(text: str) -> str:
    """Sanitize text to be compatible with latin-1 (FPDF standard font encoding)."""
    if not text:
        return ""
    # Replace common non-latin-1 characters
    replacements = {
        "\u2013": "-", # en dash
        "\u2014": "-", # em dash
        "\u2018": "'", # left single quote
        "\u2019": "'", # right single quote
        "\u201c": '"', # left double quote
        "\u201d": '"', # right double quote
        "\u2022": "*", # bullet
        "\u26a1": "[POWER]", # lightning bolt emoji
    }
    for char, replacement in replacements.items():
        text = text.replace(char, replacement)
    
    # Final strip of any other remaining non-latin-1 characters to prevent crash
    return text.encode("latin-1", "ignore").decode("latin-1")

def generate_seo_pdf(business_name, location, report):
    pdf = SEOPDFReport()
    pdf.add_page()
    
    # Title & Info
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, safe_text(f"Audit for: {business_name}"), 0, 1)
    pdf.set_font("Helvetica", "", 12)
    pdf.cell(0, 10, safe_text(f"Location: {location}"), 0, 1)
    pdf.cell(0, 10, f"Date: {report.created_at.strftime('%Y-%m-%d')}", 0, 1)
    pdf.ln(10)
    
    # Scores
    pdf.set_fill_color(240, 240, 240)
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "SEO Performance Scores", 1, 1, "L", True)
    pdf.set_font("Helvetica", "", 12)
    pdf.cell(0, 10, f"Overall Score: {report.overall_score}/100", 1, 1)
    pdf.cell(0, 10, f"Google Presence: {report.google_presence_score}/100", 1, 1)
    pdf.cell(0, 10, f"Content Quality: {report.content_score}/100", 1, 1)
    pdf.cell(0, 10, f"Social Reputation: {report.social_score}/100", 1, 1)
    pdf.ln(10)
    
    # Analysis
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "Competitor & Market Analysis", 0, 1)
    pdf.set_font("Helvetica", "", 10)
    pdf.multi_cell(0, 5, safe_text(report.competitor_analysis))
    pdf.ln(5)
    
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "Social Media & Presence Analysis", 0, 1)
    pdf.set_font("Helvetica", "", 10)
    pdf.multi_cell(0, 5, safe_text(report.social_analysis))
    pdf.ln(5)
    
    # Action Plan
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "Actionable SEO Optimization Steps", 0, 1)
    pdf.set_font("Helvetica", "", 10)
    # The actionable_steps often contain bullet points or emojis from agents
    pdf.multi_cell(0, 5, safe_text(report.actionable_steps))
    
    # Save to buffer or file
    filename = f"report_{report.id}.pdf"
    output_path = f"/tmp/{filename}"
    pdf.output(output_path)
    return output_path
