from fpdf import FPDF
import datetime

class SEOPDFReport(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 15)
        self.cell(0, 10, "Geo-Sentinel SEO Audit Report", 0, 1, "C")
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.cell(0, 10, f"Page {self.page_no()} | Generated by Geo-Sentinel Auditor", 0, 0, "C")

def test_pdf():
    pdf = SEOPDFReport()
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 16)
    
    # Simulate problematic characters like emojis or smart quotes
    business_name = "Joe's Coffee ☕"
    actionable_steps = "⚡ Step 1: Fix things.\n* Step 2: More fixes."
    
    try:
        pdf.cell(0, 10, f"Audit for: {business_name}", 0, 1)
        pdf.multi_cell(0, 5, actionable_steps)
        pdf.output("/tmp/test_debug_pdf.pdf")
        print("PDF generated successfully.")
    except Exception as e:
        print(f"FAILED: {str(e)}")

if __name__ == "__main__":
    test_pdf()
